### ISSUE TITLE
ValueError when running MACS2

### ISSUE THREAD

**Issue by kmhennick** [EngreitzLab/scE2G#40]
Hi there,

I am getting a ValueError when running MACS2 with the pipeline, shown below. From what I can tell, this is due to an incompatibility between numpy and pandas versions. I have tried upgrading, downgrading, and many other combinations of both numpy and pandas, but cannot get MACS2 to run successfully. I originally did this with python 3.11 as indicated in the documentation, but also tried with python 3.8 and ran into the same issue.

The most recent run with the attached error screenshot had numpy version 1.26.4, pandas 2.1.2, macs2 2.2.7.1, and python 3.11 (screenshot of all package versions in this env also attached).

I'm also attaching the complete log from this run where previous steps ran successfully. Let me know how best to troubleshoot, thanks in advance!

[2024-12-04T110623.436049.snakemake.log](https://github.com/user-attachments/files/18014730/2024-12-04T110623.436049.snakemake.log)
<img width="1059" alt="scE2G_valueerror" src="https://github.com/user-attachments/assets/247885c0-c788-4f02-83fc-5a6f93e16d5a">
<img width="239" alt="mambaenv_piplist" src="https://github.com/user-attachments/assets/c7dab4e3-e608-4ca6-9a67-0c3c144e7133">

**Comment by 613weilin** [comment]
Hi @kmhennick,

In our pipeline, we expect you to use macs2 installed within abc-env (in your case, it is at `snakemake/conda/d304e5d39362118ff29fab57e84c2c4e_/bin/macs2`) rather than the version you previously installed at `/home/kelsey/.local/bin/macs2`.

Could you run the command `which macs2` to check the path of macs2? If it points to the version you previously installed, you might want to remove the old macs2 folder from your `$PATH` environment variable to fix this issue.

**Comment by kmhennick** [comment]
@613weilin that fixed it, it was calling macs2 that was previously installed.

thanks so much for the help!
